apiVersion: v1
kind: Service
metadata:
  name: searchd
  labels:
    app: searchd
spec:
  clusterIP: None
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    app: searchd
---
apiVersion: v1
kind: Service
metadata:
  name: searchd-query
  labels:
    app: searchd
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    app: searchd
---
apiVersion: v1
kind: Service
metadata:
  name: searchd-ingest
  labels:
    app: searchd
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    app: searchd
